### ISSUE TITLE
[BUG] TargetEncoding op doesn't work with kfold greater than 1. 

### ISSUE THREAD

**Issue by nv-dmajchrowski** [NVIDIA/NVTabular#464] opened 2020-11-26 10:52 UTC
**Describe the bug**
When executing `NVTabular demo on Outbrain Data`, TargetEncoding operator with kfold greater than 1 is causing an error.

**Steps/Code to reproduce bug**
Run `NVTabular/examples/wnd_outbrain/Outbrain.ipynb` notebook and change TargetEncoding's `kfold` argument from 1 to 5.

**Expected behavior**
It should be possible to run the demo without any errors.

**Environment details:**
cudf version: 0.16.0
nvtabular version: 0.3.0
cuda version: 11.1
 

**Additional context**
With kfold=1 everything works fine.
With kfold=2 I'm getting the same error as for 5.
Here is corresponding stack trace log (kfold=5):
```
ValueError                                Traceback (most recent call last)
<ipython-input-13-0aecb4169adf> in <module>
      2 valid_dataset = nvt.Dataset(OUTPUT_BUCKET_FOLDER+'valid_gdf.parquet', part_mem_fraction=0.12)
      3 
----> 4 workflow.apply(train_dataset, record_stats=True, output_path=output_train_dir, shuffle=True, out_files_per_proc=5)
      5 workflow.apply(valid_dataset, record_stats=False, output_path=output_valid_dir, shuffle=False, out_files_per_proc=1)

/nvtabular/nvtabular/workflow.py in apply(self, dataset, apply_offline, record_stats, shuffle, output_path, output_format, out_files_per_proc, num_io_threads, dtypes)
    874                 out_files_per_proc=out_files_per_proc,
    875                 num_io_threads=num_io_threads,
--> 876                 dtypes=dtypes,
    877             )
    878         else:

/nvtabular/nvtabular/workflow.py in build_and_process_graph(self, dataset, end_phase, output_path, record_stats, shuffle, output_format, out_files_per_proc, apply_ops, num_io_threads, dtypes)
    989                 shuffle=shuffle,
    990                 out_files_per_proc=out_files_per_proc,
--> 991                 num_threads=num_io_threads,
    992             )
    993 

/nvtabular/nvtabular/workflow.py in ddf_to_dataset(self, output_path, shuffle, out_files_per_proc, output_format, num_threads)
   1078                 output_format,
   1079                 self.client,
-> 1080                 num_threads,
   1081             )
   1082             return

/nvtabular/nvtabular/io/dask.py in _ddf_to_dataset(ddf, fs, output_path, shuffle, out_files_per_proc, cat_names, cont_names, label_names, output_format, client, num_threads)
    110         out = client.compute(out).result()
    111     else:
--> 112         out = dask.compute(out, scheduler="synchronous")[0]
    113 
    114     # Follow-up Shuffling and _metadata creation

/conda/lib/python3.7/site-packages/dask/base.py in compute(*args, **kwargs)
    452         postcomputes.append(x.__dask_postcompute__())
    453 
--> 454     results = schedule(dsk, keys, **kwargs)
    455     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
    456 

/conda/lib/python3.7/site-packages/dask/local.py in get_sync(dsk, keys, **kwargs)
    525     """
    526     kwargs.pop("num_workers", None)  # if num_workers present, remove it
--> 527     return get_async(apply_sync, 1, dsk, keys, **kwargs)
    528 
    529 

/conda/lib/python3.7/site-packages/dask/local.py in get_async(apply_async, num_workers, dsk, result, cache, get_id, rerun_exceptions_locally, pack_exception, raise_exception, callbacks, dumps, loads, **kwargs)
    492 
    493                 while state["ready"] and len(state["running"]) < num_workers:
--> 494                     fire_task()
    495 
    496             succeeded = True

/conda/lib/python3.7/site-packages/dask/local.py in fire_task()
    464                         pack_exception,
    465                     ),
--> 466                     callback=queue.put,
    467                 )
    468 

/conda/lib/python3.7/site-packages/dask/local.py in apply_sync(func, args, kwds, callback)
    514 def apply_sync(func, args=(), kwds={}, callback=None):
    515     """ A naive synchronous version of apply_async """
--> 516     res = func(*args, **kwds)
    517     if callback is not None:
    518         callback(res)

/conda/lib/python3.7/site-packages/dask/local.py in execute_task(key, task_info, dumps, loads, get_id, pack_exception)
    225         failed = False
    226     except BaseException as e:
--> 227         result = pack_exception(e, dumps)
    228         failed = True
    229     return key, result, failed

/conda/lib/python3.7/site-packages/dask/local.py in execute_task(key, task_info, dumps, loads, get_id, pack_exception)
    220     try:
    221         task, data = loads(task_info)
--> 222         result = _execute_task(task, data)
    223         id = get_id()
    224         result = dumps((result, id))

/conda/lib/python3.7/site-packages/dask/core.py in _execute_task(arg, cache, dsk)
    119         # temporaries by their reference count and can execute certain
    120         # operations in-place.
--> 121         return func(*(_execute_task(a, cache) for a in args))
    122     elif not ishashable(arg):
    123         return arg

/conda/lib/python3.7/site-packages/dask/optimization.py in __call__(self, *args)
    961         if not len(args) == len(self.inkeys):
    962             raise ValueError("Expected %d args, got %d" % (len(self.inkeys), len(args)))
--> 963         return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))
    964 
    965     def __reduce__(self):

/conda/lib/python3.7/site-packages/dask/core.py in get(dsk, out, cache)
    149     for key in toposort(dsk):
    150         task = dsk[key]
--> 151         result = _execute_task(task, cache)
    152         cache[key] = result
    153     result = _execute_task(out, cache)

/conda/lib/python3.7/site-packages/dask/core.py in _execute_task(arg, cache, dsk)
    119         # temporaries by their reference count and can execute certain
    120         # operations in-place.
--> 121         return func(*(_execute_task(a, cache) for a in args))
    122     elif not ishashable(arg):
    123         return arg

/conda/lib/python3.7/site-packages/dask/utils.py in apply(func, args, kwargs)
     27 def apply(func, args, kwargs=None):
     28     if kwargs:
---> 29         return func(*args, **kwargs)
     30     else:
     31         return func(*args)

/conda/lib/python3.7/site-packages/dask/dataframe/core.py in apply_and_enforce(*args, **kwargs)
   5300     func = kwargs.pop("_func")
   5301     meta = kwargs.pop("_meta")
-> 5302     df = func(*args, **kwargs)
   5303     if is_dataframe_like(df) or is_series_like(df) or is_index_like(df):
   5304         if not len(df):

/nvtabular/nvtabular/workflow.py in _aggregated_op(gdf, ops)
    721         for op in ops:
    722             columns_ctx, cols_grp, target_cols, logic, stats_context = op
--> 723             gdf = logic(gdf, columns_ctx, cols_grp, target_cols, stats_context)
    724         return gdf
    725 

/conda/lib/python3.7/contextlib.py in inner(*args, **kwds)
     72         def inner(*args, **kwds):
     73             with self._recreate_cm():
---> 74                 return func(*args, **kwds)
     75         return inner
     76 

/nvtabular/nvtabular/ops/categorify.py in apply_op(self, gdf, columns_ctx, input_cols, target_cols, stats_context)
    363                 buckets=self.num_buckets,
    364                 encode_type=self.encode_type,
--> 365                 cat_names=cat_names,
    366             )
    367             if self.dtype:

/nvtabular/nvtabular/ops/categorify.py in _encode(name, storage_name, path, gdf, cat_cache, na_sentinel, freq_threshold, search_sorted, buckets, encode_type, cat_names)
    910             na_sentinel = 0
    911             labels = codes.merge(
--> 912                 value, left_on=selection_l, right_on=selection_r, how="left"
    913             ).sort_values("order")["labels"]
    914             labels.fillna(na_sentinel, inplace=True)

/conda/lib/python3.7/contextlib.py in inner(*args, **kwds)
     72         def inner(*args, **kwds):
     73             with self._recreate_cm():
---> 74                 return func(*args, **kwds)
     75         return inner
     76 

/conda/lib/python3.7/site-packages/cudf-0.16.0a0+1977.gc6dfa6e3ed-py3.7-linux-x86_64.egg/cudf/core/dataframe.py in merge(self, right, on, left_on, right_on, left_index, right_index, how, sort, lsuffix, rsuffix, type, method, indicator, suffixes)
   3983             method=method,
   3984             indicator=indicator,
-> 3985             suffixes=suffixes,
   3986         )
   3987         return gdf_result

/conda/lib/python3.7/site-packages/cudf-0.16.0a0+1977.gc6dfa6e3ed-py3.7-linux-x86_64.egg/cudf/core/frame.py in _merge(self, right, on, left_on, right_on, left_index, right_index, how, sort, lsuffix, rsuffix, method, indicator, suffixes)
   3003             suffixes,
   3004         )
-> 3005         to_return = mergeop.perform_merge()
   3006 
   3007         # If sort=True, Pandas would sort on the key columns in the

/conda/lib/python3.7/site-packages/cudf-0.16.0a0+1977.gc6dfa6e3ed-py3.7-linux-x86_64.egg/cudf/core/join/join.py in perform_merge(self)
    106         """
    107         output_dtypes = self.compute_output_dtypes()
--> 108         self.typecast_input_to_libcudf()
    109         libcudf_result = libcudf.join.join(
    110             self.lhs,

/conda/lib/python3.7/site-packages/cudf-0.16.0a0+1977.gc6dfa6e3ed-py3.7-linux-x86_64.egg/cudf/core/join/join.py in typecast_input_to_libcudf(self)
    328                 )
    329                 r_col_grp._data[r_key] = r_col_grp._data[r_key].astype(
--> 330                     to_dtype
    331                 )
    332 

/conda/lib/python3.7/site-packages/cudf-0.16.0a0+1977.gc6dfa6e3ed-py3.7-linux-x86_64.egg/cudf/core/column/column.py in astype(self, dtype, **kwargs)
    990             return self.as_timedelta_column(dtype, **kwargs)
    991         else:
--> 992             return self.as_numerical_column(dtype, **kwargs)
    993 
    994     def as_categorical_column(self, dtype, **kwargs):

/conda/lib/python3.7/site-packages/cudf-0.16.0a0+1977.gc6dfa6e3ed-py3.7-linux-x86_64.egg/cudf/core/column/string.py in as_numerical_column(self, dtype, **kwargs)
   4596             if not cpp_is_float(self).all():
   4597                 raise ValueError(
-> 4598                     "Could not convert strings to float "
   4599                     "type due to presence of non-floating values."
   4600                 )

ValueError: Could not convert strings to float type due to presence of non-floating values.```

**Comment by EvenOldridge** [comment] 2020-11-26 17:51
@nv-dmajchrowski Can you share the code that instantiates the op along with the types of data in the column you're encoding.  Also helpful to know if there are any nulls, although why it would work for k-fold 0 and not 5 I'm unsure.  @rnyak you had this working on outbrains right?.

**Comment by rnyak** [comment] 2020-11-26 19:31
@nv-dmajchrowski Dawid thanks for reporting, can you please share your NVT workflow and FE code so I can check. Thanks.

**Comment by benfred** [comment] 2020-11-27 00:19
@rnyak I've reproduced this bug against the latest NVT - just changing the kfold param in the examples/wnd_outbrain/Outbrain.ipynb is sufficient to trigger this.

It's interesting that changing a TargetEncoding parameter is causing an exception in the Categorify op though - I'm wondering if this is related to the two operators both using the GroupByStatistics statoperator to calculate statistics.

**Comment by nv-dmajchrowski** [comment] 2020-11-30 09:19
@EvenOldridge  @rnyak 
Exactly as @benfred mentioned above, I used the demo from the NVT repository so you can check the code in the 
examples/wnd_outbrain/Outbrain.ipynb notebook to see corresponding NVT workflow.

**Comment by rnyak** [comment] 2020-11-30 19:05
> @EvenOldridge @rnyak
> Exactly as @benfred mentioned above, I used the demo from the NVT repository so you can check the code in the
> examples/wnd_outbrain/Outbrain.ipynb notebook to see corresponding NVT workflow.

yes I could reproduce the error too. will debug and see what's going on. @benfred yes, I also believe `two operators both using the GroupByStatistics statoperator to calculate statistics.` could be the reason.

**Comment by benfred** [comment] 2021-01-07 17:36
This is fixed with the new API changes

**Closed by benfred** 2021-01-07 17:36 UTC
Labels: P0, bug
