### ISSUE TITLE
[BUG] Data loader performance drops

### ISSUE THREAD

**Issue by nv-dmajchrowski** [NVIDIA/NVTabular#888] opened 2021-06-14 10:01 UTC
**Describe the bug**
I'm measuring throughput using KerasSequenceLoader and I'm experiencing nondeterministic performance drops from time to time. For example measuring throughput (number of samples per second) as batch_size / (interval between end of 2 consecutive training steps), I'm getting following log:

> Throughput: 722936.7608146777
> Throughput: 688348.6117203963
> Throughput: 312013.7879906468
> Throughput: 624850.3260757882
> Throughput: 501142.4869421744
> Throughput: 229585.7952262529
> Throughput: 617169.8991410793
> Throughput: 711681.9645554414

Additionally I've calculated the median - 686733 and the mean throughput - 666872 +/- 79903 (without first and last batch of each epoch). Those drops are clearly below the std inverval, also there are no such picks over the interval.

**Steps/Code to reproduce bug**

0. Use NVTabular/examples/advanced-ops-outbrain/ jupyter notebooks as an example

1. In last notebook (03-Training) add following cell (before last one):
```
import time

class ThroughputMeasurement(tf.keras.callbacks.Callback):
    def __init__(self):
        self.t0 = None
        self.batch_start = None
        self.bs = 131072
        
    def on_train_begin(self, logs=None):
        self.batch_start = time.time()
        
    def on_train_batch_end(self, batch, logs=None):
        throughput = self.bs / (time.time() - self.batch_start)
        print(f"Throughput: {throughput}")
        self.batch_start = time.time()
        
throughput_callback = ThroughputMeasurement()
```
2. Call the last cell with:
```
history = wide_and_deep_model.fit(train_dataset_tf, verbose=0, callbacks=[validation_callback, throughput_callback], epochs=2)
```

**Expected behavior**
Constant (with respect to variance) throughput measurement without drops during training.

**Environment details (please complete the following information):**
 - Environment location: Docker
 - Method of NVTabular install: 
   - `docker pull nvcr.io/nvidia/merlin/merlin-tensorflow-training:0.5.3`
   - `nvidia-docker run --rm -it --net=host --ipc=host ${IMAGE} bash`
   - `cd /nvtabular && git checkout main && git pull` (corresponds to 95edc4c9cb437913fffab1b44fe1b4e13701088f)
 

**Additional context**
- The problem is even more visible in case of multi-gpu training, but the single-gpu example is enough to reproduce
- 1xGV100 32GB card was used for the tests

**Comment by jperez999** [comment] 2021-07-19 17:09
The behavior you are seeing is happening because you have a small number of partitions and those partitions are not all the same size. Some of the partitions will be smaller than others, this  happens because the data loader does not support reading from more than one file to create a "target_size" partition, so you end up with partitions with "< target_size" records. That behavior can be added in future releases.

**Comment by benfred** [comment] 2021-10-06 17:39
Closing as duplicate of https://github.com/NVIDIA/NVTabular/issues/1142

**Closed by benfred** 2021-10-06 17:39 UTC
Labels: bug
