### ISSUE TITLE
[BUG] NVTabular produces no correct metadata for HugeCTR with new API

### ISSUE THREAD

**Issue by bschifferer** [NVIDIA/NVTabular#518] opened 2021-01-07 15:27 UTC
**Describe the bug**
NVTabular workflow creates `_metadata.json` for HugeCTR parquet reader. The json parameter 'cats', 'conts' and 'labels' are empty

Example:
```
{"file_stats": [{"file_name": "0.00b31beaa597447f8eca372c8fbde55d.parquet", "num_rows": 337838}], "cats": [], "conts": [], "labels": []}
```

**Steps/Code to reproduce bug**
Run a workflow/example with `shuffle=nvt.io.Shuffle.PER_PARTITION` in .transform function

**Expected behavior**
NVTabular workflow should produce correct cats, conts and label output

**Comment by benfred** [comment] 2021-01-11 18:17
We need to update the hugectr notebook: https://nvidia.github.io/NVTabular/main/api/dataset.html#nvtabular.io.dataset.Dataset.to_parquet

**Comment by benfred** [comment] 2021-02-01 18:32
duplicate of #519

**Closed by benfred** 2021-02-01 18:32 UTC
Labels: bug
