### ISSUE TITLE
[BUG] JoinGroupby + LambdaOp error in NVT workflow

### ISSUE THREAD

**Issue by rnyak** [NVIDIA/NVTabular#229] opened 2020-08-20 21:54 UTC
**Describe the bug**

I cannot use LambdaOp after JoinGroupby op in an NVT workflow.  I am getting `NotImplementedError: A Column with duplicate name found: ad_id_count, cuDF    doesn't support having multiple columns with  same names yet.`. 

**Steps/Code to reproduce bug**

A min rep example can be found below:
```
gdf_test = cudf.DataFrame({'ad_id': [1, 2, 2, 6, 6, 8, 3, 3], 'source_id': [2, 4, 4, 7, 5, 2, 5, 2], 'platform':[1, 2, np.nan, 2, 1, 3, 3, 1],'clicked': [1 , 0, 1, 0, 0, 1, 1, 0]})

proc = nvt.Workflow(
    cat_names=['ad_id', 'source_id', 'platform'],
    cont_names= [],
    label_name=['clicked'])
#apply dropna
proc.add_feature(
    [
    Dropna(['platform']),
    JoinGroupby(columns=['ad_id'], 
                cont_names=['clicked'], 
                stats=['sum','count'])
    ])
proc.add_preprocess(
    LambdaOp(
        op_name='ctr',
        f=lambda col, gdf: col/gdf['ad_id_count'],
        columns=['ad_id_clicked_sum'],
        replace=False))
proc.finalize()
GPU_MEMORY_FRAC = 0.2
train_dataset = nvt.Dataset(gdf_test, engine='parquet',  part_mem_fraction=GPU_MEMORY_FRAC)
proc.apply(train_dataset, apply_offline=True, record_stats=True, output_path='./preprocessed/', shuffle=False, out_files_per_proc=1)
```

**Comment by rnyak** [comment] 2020-08-20 21:57
@jperez999 @rjzamora @bschifferer for viz.

**Comment by rjzamora** [comment] 2020-08-20 22:12
Thanks @rnyak - Julio just mentioned offline that this is likely a duplicate of #212

**Comment by rnyak** [comment] 2020-08-24 20:01
@benfred

**Closed** 2020-08-25 21:16 UTC
Labels: bug
